### ISSUE TITLE
Feedback from Sue on Project 1

### ISSUE THREAD

**Issue by meadowsage2016** [pknibbe/repertoire#3]
# Design/Code Review 1

#### Reviewer:  Sue Hundt

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Does it exist?| The problem Statement was very complete.  |
| |Does the problem statement accurately describe project purpose?|   Yes it gives a clear picture of the focus of the project.|
| |Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.|  Yes|
| |What is good?| Yes | 
| |What could be improved?| | 
|**Design Documentation**|Does it exist?|Yes.| 
| |Is the navigation/flow through the application logical and easy to use?|Yes | 
| Is the order in which the fields are displayed and form fields entered logical and easy to use?| Yes |
| |What data is missing?| No |
| |Is there data that is not used?| Probably not|
| |What is good?| Yes |
| |What could be improved?| |
|**Data model**|Does it exist?| |
| |Is everything on the screens represented in the model?|Yes the data model was complete. |  
| |Does the model represent good database design? |It was a different way of modeling databases where the associations are kept in a separate table.  Different from what I have ever seen.  Interesting! |
| |What is good?| Yes|
| |What could be better?| |
|**Additional design documents**| | |
|**Application structure in IntelliJ**|Does it exist?|  I don't recall, my mistake. |
|**Entities/DAOs/Controllers**|Do they exist?|  Yes|
|**Java code quality**|Are methods single-purpose?| Did not look that closely.  |
| |Do the DAOs use Hibernate? No hard-coded sql!| Yes |
|**Logging**|Has log4J been added?| Not sure.|
|**Unit Tests**|Do they exist?|Not sure |
|**Web Service/API integration**|Has a web service/api been selected? |No| 
| |What web services/apis might work well with this application?|song data base that copies in album data | 
 | |Other comments/notes?| Peter was very well prepared.  I think having the user build their song lists with entering meta data is a mistake.  A hit list of available songs that would bring in the meta data would be less prone to errors.  I regret that I was not well prepared to do the Code Review correctly.  This is my fault.  I will follow the feedback form next time and hit all areas.  Sorry Peter!  |

**Comment by pknibbe** [comment]
Thanks
