### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by PunithaAnandan** [pknibbe/repertoire#6]
# Design/Code Review 2

#### Reviewer: Punitha Anandan

|Category|Criteria|Analysis/Comments|
|--------|---------|---------------|
|**Running application**|| |
| |Describe the application functionality that has been built and is working.| Getting Error|
| |What is good?|None|
| |What could be improved?|None|
|**Unit Tests**|| |
| |What are the code coverage statistics?|Not exactly| 
| |Are @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code?|Yes| 
|**JSPs**|| |
| | Is templating used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.)|Yes|
| |What is good?|used jstl|
| |What could be improved?|Form and loop stay in seperate jsp.(accounts.jsp), avoid repeated codes .jsps ("mainpanel.jsp, mainpanel.jsp.orig", "uploadSong.jsp,uploadSong.jsp.orig")|
|**Code quality**|| |
| |Are methods single-purpose?|Yes|
| |Are classes appropriately-sized classes (no monster classes)?|Yes|
| |Are the same lines of code repeated at all?|some places (repeated codes in "UserDAO.java.orig, UserDAO.java")| 
| |Do any classes perform very similar functions that could be candidates for super/subclass relationships?|some places|
| |Are any values hard-coded that should be in a properties file?|No|
| |Are variable names descriptive?|Most of the time|
| |Are there many branches or loops that could be simplified or broken up into smaller methods?|Some places|
| |Do the DAOs use Hibernate? No hard-coded sql!|Yes|
| |Has log4J been added?|Yes|
| |Are there logging statements in the code?|Yes|
| |Are appropriate logging levels used? Info, debug, error, for example.|"Info" only used in all DAOs|
| |Are there any System.out.printlns in the code?|None|
| |Other comments/notes?|Try to use full description variable names. ( use "association" instead of "a"), Try to break if ...else in seperate methods for code clarity(RoleAndUserManager.java)|
|**Web Service/API integration**|Which web service/api is being used? |MyTunes Amazon Prime|
| |Is the integration built?|No|
| | If so, evaluate the integration code. What is good? What could use improvement?
|**Independent research topic**|What is the developer's independent research topic?|Amazon Prime music streaming|
| |Has the topic been implemented in the project?|No|
| |If so, evaluate the implementation. What is good? What could use improvement?|  |
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.|Different test methods otherthan basic ones,Use "final", Add Referrence.md for the "Steps to use AWS XXXproject"|

**Comment by pknibbe** [comment]
Thank you.
